apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/capstone-devops/gitops-manifests.git'
    targetRevision: HEAD
    path: helm/hello-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
